
version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs:4566
      - DOCKER_HOST=unix:///var/run/docker.sock

  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
